var annotated_dup =
[
    [ "Eigen", "namespace_eigen.html", [
      [ "NumTraits< gbLAB::Rational< IntScalarType > >", "struct_eigen_1_1_num_traits_3_01gb_l_a_b_1_1_rational_3_01_int_scalar_type_01_4_01_4.html", "struct_eigen_1_1_num_traits_3_01gb_l_a_b_1_1_rational_3_01_int_scalar_type_01_4_01_4" ]
    ] ],
    [ "gbLAB", "namespacegb_l_a_b.html", [
      [ "BestRationalApproximation", "classgb_l_a_b_1_1_best_rational_approximation.html", "classgb_l_a_b_1_1_best_rational_approximation" ],
      [ "BiCrystal", "classgb_l_a_b_1_1_bi_crystal.html", "classgb_l_a_b_1_1_bi_crystal" ],
      [ "BicrystalActor", "structgb_l_a_b_1_1_bicrystal_actor.html", "structgb_l_a_b_1_1_bicrystal_actor" ],
      [ "CanonicalTP", "classgb_l_a_b_1_1_canonical_t_p.html", "classgb_l_a_b_1_1_canonical_t_p" ],
      [ "Diff", "classgb_l_a_b_1_1_diff.html", "classgb_l_a_b_1_1_diff" ],
      [ "DiophantineSolver", "classgb_l_a_b_1_1_diophantine_solver.html", "classgb_l_a_b_1_1_diophantine_solver" ],
      [ "DislocationDipole", "classgb_l_a_b_1_1_dislocation_dipole.html", "classgb_l_a_b_1_1_dislocation_dipole" ],
      [ "Dislocations", "classgb_l_a_b_1_1_dislocations.html", "classgb_l_a_b_1_1_dislocations" ],
      [ "DisplacementKernel", "classgb_l_a_b_1_1_displacement_kernel.html", "classgb_l_a_b_1_1_displacement_kernel" ],
      [ "Ensemble", "classgb_l_a_b_1_1_ensemble.html", "classgb_l_a_b_1_1_ensemble" ],
      [ "EvolutionAlgorithm", "classgb_l_a_b_1_1_evolution_algorithm.html", "classgb_l_a_b_1_1_evolution_algorithm" ],
      [ "Exponential", "classgb_l_a_b_1_1_exponential.html", "classgb_l_a_b_1_1_exponential" ],
      [ "Fraction", "structgb_l_a_b_1_1_fraction.html", "structgb_l_a_b_1_1_fraction" ],
      [ "Function", "classgb_l_a_b_1_1_function.html", "classgb_l_a_b_1_1_function" ],
      [ "Gb", "classgb_l_a_b_1_1_gb.html", "classgb_l_a_b_1_1_gb" ],
      [ "GbContinuum", "classgb_l_a_b_1_1_gb_continuum.html", "classgb_l_a_b_1_1_gb_continuum" ],
      [ "GbMaterialTensors", "classgb_l_a_b_1_1_gb_material_tensors.html", "classgb_l_a_b_1_1_gb_material_tensors" ],
      [ "GbMesoState", "classgb_l_a_b_1_1_gb_meso_state.html", "classgb_l_a_b_1_1_gb_meso_state" ],
      [ "GbMesoStateEnsemble", "classgb_l_a_b_1_1_gb_meso_state_ensemble.html", "classgb_l_a_b_1_1_gb_meso_state_ensemble" ],
      [ "GbShifts", "classgb_l_a_b_1_1_gb_shifts.html", "classgb_l_a_b_1_1_gb_shifts" ],
      [ "GramMatrix", "classgb_l_a_b_1_1_gram_matrix.html", "classgb_l_a_b_1_1_gram_matrix" ],
      [ "HhatInvFunction", "classgb_l_a_b_1_1_hhat_inv_function.html", "classgb_l_a_b_1_1_hhat_inv_function" ],
      [ "IntegerLattice", "classgb_l_a_b_1_1_integer_lattice.html", "classgb_l_a_b_1_1_integer_lattice" ],
      [ "IntegerMath", "structgb_l_a_b_1_1_integer_math.html", "structgb_l_a_b_1_1_integer_math" ],
      [ "LandauWangTP", "classgb_l_a_b_1_1_landau_wang_t_p.html", "classgb_l_a_b_1_1_landau_wang_t_p" ],
      [ "Lattice", "classgb_l_a_b_1_1_lattice.html", "classgb_l_a_b_1_1_lattice" ],
      [ "LatticeCore", "structgb_l_a_b_1_1_lattice_core.html", "structgb_l_a_b_1_1_lattice_core" ],
      [ "LatticeDirection", "structgb_l_a_b_1_1_lattice_direction.html", "structgb_l_a_b_1_1_lattice_direction" ],
      [ "LatticeFunction", "classgb_l_a_b_1_1_lattice_function.html", "classgb_l_a_b_1_1_lattice_function" ],
      [ "LatticeVector", "classgb_l_a_b_1_1_lattice_vector.html", "classgb_l_a_b_1_1_lattice_vector" ],
      [ "LLL", "classgb_l_a_b_1_1_l_l_l.html", "classgb_l_a_b_1_1_l_l_l" ],
      [ "MatrixDimIExt", "classgb_l_a_b_1_1_matrix_dim_i_ext.html", "classgb_l_a_b_1_1_matrix_dim_i_ext" ],
      [ "MatrixDimIExt< IntScalarType, 1 >", "classgb_l_a_b_1_1_matrix_dim_i_ext_3_01_int_scalar_type_00_011_01_4.html", "classgb_l_a_b_1_1_matrix_dim_i_ext_3_01_int_scalar_type_00_011_01_4" ],
      [ "MesoState", "classgb_l_a_b_1_1_meso_state.html", "classgb_l_a_b_1_1_meso_state" ],
      [ "MesoStateEnsemble", "classgb_l_a_b_1_1_meso_state_ensemble.html", "classgb_l_a_b_1_1_meso_state_ensemble" ],
      [ "MonteCarlo", "classgb_l_a_b_1_1_monte_carlo.html", "classgb_l_a_b_1_1_monte_carlo" ],
      [ "oiViewerMainWindow", "structgb_l_a_b_1_1oi_viewer_main_window.html", "structgb_l_a_b_1_1oi_viewer_main_window" ],
      [ "oiViewerVTKwidget", "structgb_l_a_b_1_1oi_viewer_v_t_kwidget.html", "structgb_l_a_b_1_1oi_viewer_v_t_kwidget" ],
      [ "Operator", "classgb_l_a_b_1_1_operator.html", "classgb_l_a_b_1_1_operator" ],
      [ "OperatorScalarProduct", "classgb_l_a_b_1_1_operator_scalar_product.html", "classgb_l_a_b_1_1_operator_scalar_product" ],
      [ "OperatorSum", "classgb_l_a_b_1_1_operator_sum.html", "classgb_l_a_b_1_1_operator_sum" ],
      [ "OrderedTuplet", "classgb_l_a_b_1_1_ordered_tuplet.html", "classgb_l_a_b_1_1_ordered_tuplet" ],
      [ "PeriodicFunction", "classgb_l_a_b_1_1_periodic_function.html", "classgb_l_a_b_1_1_periodic_function" ],
      [ "Rational", "structgb_l_a_b_1_1_rational.html", "structgb_l_a_b_1_1_rational" ],
      [ "RationalApproximations", "classgb_l_a_b_1_1_rational_approximations.html", "classgb_l_a_b_1_1_rational_approximations" ],
      [ "RationalLatticeDirection", "structgb_l_a_b_1_1_rational_lattice_direction.html", "structgb_l_a_b_1_1_rational_lattice_direction" ],
      [ "RationalMatrix", "classgb_l_a_b_1_1_rational_matrix.html", "classgb_l_a_b_1_1_rational_matrix" ],
      [ "RationalReciprocalLatticeDirection", "structgb_l_a_b_1_1_rational_reciprocal_lattice_direction.html", "structgb_l_a_b_1_1_rational_reciprocal_lattice_direction" ],
      [ "ReciprocalLatticeDirection", "structgb_l_a_b_1_1_reciprocal_lattice_direction.html", "structgb_l_a_b_1_1_reciprocal_lattice_direction" ],
      [ "ReciprocalLatticeVector", "classgb_l_a_b_1_1_reciprocal_lattice_vector.html", "classgb_l_a_b_1_1_reciprocal_lattice_vector" ],
      [ "ReferenceState", "classgb_l_a_b_1_1_reference_state.html", "classgb_l_a_b_1_1_reference_state" ],
      [ "RLLL", "classgb_l_a_b_1_1_r_l_l_l.html", "classgb_l_a_b_1_1_r_l_l_l" ],
      [ "Shift", "classgb_l_a_b_1_1_shift.html", "classgb_l_a_b_1_1_shift" ],
      [ "ShiftedDisplacementKernelFT", "classgb_l_a_b_1_1_shifted_displacement_kernel_f_t.html", "classgb_l_a_b_1_1_shifted_displacement_kernel_f_t" ],
      [ "SmithDecomposition", "classgb_l_a_b_1_1_smith_decomposition.html", "classgb_l_a_b_1_1_smith_decomposition" ],
      [ "SmithDecomposition< 1 >", "classgb_l_a_b_1_1_smith_decomposition_3_011_01_4.html", "classgb_l_a_b_1_1_smith_decomposition_3_011_01_4" ],
      [ "StaticID", "classgb_l_a_b_1_1_static_i_d.html", "classgb_l_a_b_1_1_static_i_d" ],
      [ "StringToScalar", "structgb_l_a_b_1_1_string_to_scalar.html", "structgb_l_a_b_1_1_string_to_scalar" ],
      [ "StringToScalar< double >", "structgb_l_a_b_1_1_string_to_scalar_3_01double_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01double_01_4" ],
      [ "StringToScalar< float >", "structgb_l_a_b_1_1_string_to_scalar_3_01float_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01float_01_4" ],
      [ "StringToScalar< int >", "structgb_l_a_b_1_1_string_to_scalar_3_01int_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01int_01_4" ],
      [ "StringToScalar< long >", "structgb_l_a_b_1_1_string_to_scalar_3_01long_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01long_01_4" ],
      [ "StringToScalar< long double >", "structgb_l_a_b_1_1_string_to_scalar_3_01long_01double_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01long_01double_01_4" ],
      [ "StringToScalar< long long >", "structgb_l_a_b_1_1_string_to_scalar_3_01long_01long_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01long_01long_01_4" ],
      [ "StringToScalar< unsigned long >", "structgb_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01_4" ],
      [ "StringToScalar< unsigned long long >", "structgb_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01long_01_4.html", "structgb_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01long_01_4" ],
      [ "TextFileParser", "classgb_l_a_b_1_1_text_file_parser.html", "classgb_l_a_b_1_1_text_file_parser" ],
      [ "XTuplet", "classgb_l_a_b_1_1_x_tuplet.html", "classgb_l_a_b_1_1_x_tuplet" ]
    ] ],
    [ "pyoilab", "namespacepyoilab.html", [
      [ "PyLatticeDirection", "classpyoilab_1_1_py_lattice_direction.html", "classpyoilab_1_1_py_lattice_direction" ],
      [ "PyLatticeVector", "classpyoilab_1_1_py_lattice_vector.html", "classpyoilab_1_1_py_lattice_vector" ],
      [ "PyReciprocalLatticeDirection", "classpyoilab_1_1_py_reciprocal_lattice_direction.html", "classpyoilab_1_1_py_reciprocal_lattice_direction" ],
      [ "PyReciprocalLatticeVector", "classpyoilab_1_1_py_reciprocal_lattice_vector.html", "classpyoilab_1_1_py_reciprocal_lattice_vector" ]
    ] ],
    [ "FFT", "class_f_f_t.html", "class_f_f_t" ],
    [ "range", "classrange.html", "classrange" ],
    [ "Rotation", "class_rotation.html", "class_rotation" ]
];